import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={cn(
          "bg-white Pretendard-Regular antialiased ",
          fontSans.variable
        )}
      >
        <div className="bg-custom-background max-w-[500px] min-h-[100vh] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}


