import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={cn(
          "bg-white font-sans antialiased ",
          fontSans.variable
        )}
      >
        <div className="bg-custom-background max-w-[500px] min-h-[100vh]">
          <div className="w-full fixed top-0 mb-4">
            <Header />
          </div>
          <div className="h-[86px]"></div>
          <div className="pb-[108px]">
            {children}
          </div>
          <div className="fixed bottom-0 w-full">
            <div className="max-w-[500px] h-[86px] grid content-between bg-white pt-4">
              <Footer />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}


